services:
  - type: web
    name: stock-tracker-api
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn stock-tracker-backend:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
